apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-infra-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eliezeribghi/first-todo-list.git
    targetRevision: terraform-argocd
    path: aws_infrastructure/environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true