
apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-infra-dev
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        command:
        - /bin/sh
        - -c
        - |
            git clone https://github.com/eliezeribghi/first-todo-list.git /workspace/repo
            cd /workspace/repo/aws_infrastructure/environments/dev
            terraform init
            terraform apply -auto-approve
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
          - name: workspace
            mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir: {}
      restartPolicy: Never


       