apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-apply
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: terraform
        image: hashicorp/terraform:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        command:
        - /bin/sh
        - -c
        - |
          terraform init
          terraform apply -auto-approve
        workingDir: /workspace
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      volumes:
      - name: workspace
        emptyDir: {}
      restartPolicy: Never