
name: Laravel

on:
  push:
    branches:  github-action
    tags:  'v*.*.*' 
  pull_request:
    branches:  main 

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and tag Docker image
      run: |
        # Construire l'image avec docker-compose
        docker-compose build backend
        # Taguer avec le numéro de version (si tag Git)
        if [[ "${{ github.ref }}" =~ ^refs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
          docker tag backend:latest my-backend:${BASH_REMATCH[1]}
        fi
        # Taguer avec latest pour les push sur main
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          docker tag backend:latest my-backend:latest
        fi
        # Taguer avec le hash du commit
        docker tag backend:latest my-backend:${{ github.sha }}
    - name: Start Docker containers
      run: docker-compose up -d

    - name: Install Dependencies
      run: docker-compose exec -T backend_container php composer install
    - name: Generate key
      run: docker-compose exec -T backend_container php artisan key:generate
    - name: Run Tests
      run: docker-compose exec -T backend_container php artisan test
    - name: Stop Docker containers
      run: docker-compose down