name: Terraform CI/CD

on:
  push:
    branches: [master, test-argo]
    tags: ['v*.*.*']

  pull_request:
    branches: [master, test-argo]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout   code
        uses: actions/checkout@v3 # Récupère le code du dépôt

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2 # Installe Terraform
        with:
          terraform_version: 1.5.0 # Version de Terraform

      - name: Terraform Init
        run: terraform init # Initialise le projet Terraform

      - name: Terraform Validate
        run: terraform validate # Valide la syntaxe des fichiers Terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan # Génère un plan de déploiement
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # Clé AWS pour l'authentification
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Clé secrète AWS

      - name: Terraform Apply
        if: github.event_name == 'push' # Applique uniquement sur un push (pas sur PR)
        run: terraform apply -auto-approve tfplan # Applique le plan Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # Clé AWS pour l'authentification
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Clé secrète AWS
